# Generated by Django 3.0.5 on 2020-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('maxpeople', models.IntegerField(default=1)),
                ('photoroom', models.ImageField(default='defaultroom.jpg', upload_to='room_pictures')),
                ('photodesc', models.CharField(default='This is the room!', max_length=250)),
                ('tetragwnika', models.IntegerField(default=0)),
                ('roomtypes', models.CharField(choices=[('Studio', 'Studio'), ('Double', 'Double'), ('Family', 'Family')], default='Studio', max_length=20)),
                ('is_reserved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
