# Generated by Django 3.0.5 on 2020-04-30 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('customerid', models.IntegerField()),
                ('phone', models.CharField(max_length=9)),
                ('bookIn', models.DateField(default=django.utils.timezone.now, verbose_name='Book in date')),
                ('bookOut', models.DateField(default=django.utils.timezone.now, verbose_name='Book out date')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room')),
            ],
        ),
    ]
