# Generated by Django 3.0.5 on 2020-04-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
