# Generated by Django 3.0.5 on 2020-05-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='author',
            new_name='customer',
        ),
    ]
