# Generated by Django 3.0.5 on 2020-05-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20200502_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.IntegerField(default=1),
        ),
    ]
